### ISSUE TITLE
Exporting orders?

### ISSUE THREAD

**Issue by surfjedi** [swipestripe/silverstripe-swipestripe#11]
I was have look around to se how to get a CSV export of orders- and found that you've removed the 'gridFieldExportButton' in ShopAdmin.php line 142. Even tho its set to show 'before' on line 135.

Was there any reason for this to the functionally? 

I have changed line138-142 to get basic export going:
        $fieldConfig = GridFieldConfig_RecordEditor::create($this->stat('page_length'))
                ->addComponent($exportButton)
                ->removeComponentsByType('GridFieldFilterHeader');
                //->removeComponentsByType('GridFieldToolbarHeader')
                // ->removeComponentsByType('GridFieldExportButton');

**Comment by frankmullenger** [comment]
Thanks Lee, I think I left exporting out until I could check that the resulting CSV file was well formatted. Seems to be pretty good.
