### ISSUE TITLE
Add product to shopping cart and AJAX feature.

### ISSUE THREAD

**Issue by ghost** [swipestripe/silverstripe-swipestripe#13]
Hi Frank!

When you add a product in the web page (click button), the web page refresh completely or this is done by AJAX?
If the answer is no. Are you going to include this feature in swipestripe?
When?

Thanks,
Regards,
Jose A.

**Comment by frankmullenger** [comment]
Hi Jose, it is a form submission/page reload at the moment. Would not be hard to change to AJAX if you liked. You can also replace the ProductForm entirely using Object::use_custom_class() if you like. This sort of question might be best suited to the SilverStripe ecommerce forum mate, thanks!
