### ISSUE TITLE
Currency, Category, Coupon , Addresses , Tax, Shipping, Downloadable , ... Open Source?

### ISSUE THREAD

**Issue by ghost** [swipestripe/silverstripe-swipestripe#14]
Hi Frank!

From what I see now SwipeStripe is open source.
Does the rest of modules are open source?
Currency, Category, Coupon , Addresses , Tax, Shipping, Downloadable , ...

Thanks,
Regards,
Jose A.

**Comment by frankmullenger** [comment]
Hi Jose, yes the latest version of SwipeStripe is using an open source license now, the rest of the modules will be moved to the same license over the coming weeks. Thanks for the questions but it might be better to keep questions like this in the SilverStripe [forum](http://www.silverstripe.org/e-commerce-modules/) or email me directly using the contact form on [SwipeStripe.com](http://swipestripe.com).
