### ISSUE TITLE
No attributes seem to be shown.

### ISSUE THREAD

**Issue by sayhitovincent** [swipestripe/silverstripe-swipestripe#18]
I've got 2 fresh installations of SwipeStripe on Silverstripe 3.1.0-rc1 and 3.1.1 and neither seem to show attributes on product pages.

I've tested the data entered on the demo site within my installations and neither seem to be working. They're also on PHP 5.4 and 5.5

**Comment by frankmullenger** [comment]
Hi Vincent, thanks for reporting this will give it a test soon to confirm.

**Comment by icecaster** [comment]
@sayhitovincent Are you using IE by any chance?

**Comment by sayhitovincent** [comment]
I'm using Chrome on Ubuntu, which is kept up to date.

**Comment by gordonbanderson** [comment]
I ran into this issue as well after I'd installed SwipeStripe for the first time.  However it may have been an newb issue as I had not added a variation for each option.  When I did this, I saw the dropdown as expected.

**Comment by frankmullenger** [comment]
Ohh, right. Yes you will need variations as well as product attributes @sayhitovincent, is that possibly the issue? The variations are necessary so that different combinations of attributes can be created and have prices associated with them.

**Comment by sayhitovincent** [comment]
Ok, that makes a bit more sense.... Are you able to make some sort of message within the admin to explain that these attributes won't show without variations? Perhaps after the attribute is saved?

**Comment by frankmullenger** [comment]
Ok yes we can look at making this more obvious with documentation. I will close this ticket for now then and make a note of the need for better docs.

**Comment by mhenden** [comment]
I've got the same problem except I have both ATTRIBUTES and VARIATIONS loaded. This has produced an empty dropdown menu. What gives?
