### ISSUE TITLE
Pre population not working as expected.

### ISSUE THREAD

**Issue by icecaster** [swipestripe/silverstripe-swipestripe#2]
Hey Frank,

just realised the cart and checkout page arent being created as expected.

I am unable to create them manually, will provide more details soon.

Cheers

PS.

the site is coming together nicely:
http://chillshop.chillstudio.co.nz/

**Comment by frankmullenger** [comment]
Really? that is strange. the requireDefaultRecords() on the CartPage and CheckoutPage should be taking care of that. Is there a page of type CartPage or CheckoutPage already in your db? Did you have any problems installing SwipeStripe and running an initial dev/build?

**Comment by icecaster** [comment]
Yes, I entered the DB access details wrong. This caused the initial dev build to fail.
Would this be the reason for SS to ignore require default records?

the pages home, about and contact us were created successfully, just the swipestripe pages are missing.
Is there any way of manually creating them, in case someone deleted them through the cms?

**Comment by frankmullenger** [comment]
If you run a dev/build again, and there are not pages existing in the DB of type CartPage, CheckoutPage, AccountPage - those pages should be created again for you by the requireDefaultRecords()...

**Comment by frankmullenger** [comment]
Running the dev/build?flush=1 seemed to fix this issue, not sure why it didn't work for you - maybe it required the ?flush=1 ?
