### ISSUE TITLE
Why was stock level removed?

### ISSUE THREAD

**Issue by gordonbanderson** [swipestripe/silverstripe-swipestripe#20]
I've been trying to figure out how to enable stock level functionality, and by searching through the code I saw several comments relating to stock level.  However it appears to have been removed, see https://github.com/frankmullenger/silverstripe-swipestripe/commit/0bc5d0a3338d31fa166161246349c87bebfee4e9 for the relevant commit for Product, and https://github.com/frankmullenger/silverstripe-swipestripe/commit/0bc5d0a3338d31fa166161246349c87bebfee4e9 for Variation.

Why was this done, as it seems like fairly core functionality for any shopping cart application.  Is the intention to move this functionality to a separate module, and if so does this module exist?

**Comment by frankmullenger** [comment]
Hi @gordonbanderson, yes exactly - it was removed to go into a separate module. Currently that module does not exist, but it should and hopefully will soon. 

The reason for removal was to try and keep the code more modular, simpler to maintain and easier for contributors to manage. Also, stock management can be built a few different ways and it isn't always clear which is the best way.

For instance, would you expect the items in stock to go down once an item is placed into a cart? So that once I put an item in the cart another customer cannot buy it unless I abandon the cart or complete my order? Or would you be happy with reducing stock level once an order is complete?

**Comment by gordonbanderson** [comment]
Hi @frankmullenger , thanks for the prompt feedback.  And good to know a module is in the pipeline :)

**Comment by Cumquat** [comment]
Hi just found this plugin and it looks great, any news on the stock module?

**Comment by Zauberfisch** [comment]
not that I am aware of, however it is fairly simple to implement it yourself.
In my current project I have a simple stock count implement in just a few lines.

I create a DataObject "Stock" with just an Int containing the current number of items in stock.
Product has_one Stock (I put that into an separate DataObject so I don't have to update Product and Product_Live when i change the stock, makes things easier, thanks to @frankmullenger for the idea).

Then I have a DataExtension to the Order and hook into `onAfterPayment`. If the payment was successful, I count down the stock.

that's pretty much it.

**Comment by stevie-mayhew** [comment]
I've got a module for this which I am looking to release next week - theres a bit of code cleanup and documentation to do.

**Comment by Cumquat** [comment]
Thanks for that Zauberfisch  and  stevie-mayhew  look forward to seeing it.

Thanks guys.

Mick

**Comment by digitweaks** [comment]
Any chance to see the stock level back in SwipeStripe or a tutorial to implement it ? I spent hours trying to get stock control to work with no results.

**Comment by jordanmkoncz** [comment]
Hey, any updates on when the separate inventory management module will be released?

**Comment by edlinklater** [comment]
@stevie-mayhew Is it next week yet? :laughing:

**Comment by stevie-mayhew** [comment]
No :cry: 

I'm not happy with the solution we have - its pretty specific to our stack and I have yet to have time to work on this.

**Comment by adrian-stein** [comment]
@frankmullenger any word on the stock level module yet? It would be really useful for me right now!! :)

**Comment by frankmullenger** [comment]
@adrian-stein sorry, haven't had a chance to tackle this yet. @stevie-mayhew might have something available but not sure yet.

**Comment by stevie-mayhew** [comment]
@adrian-stein we have something that is a WIP that can be released, although it doesn't solve all the problems of stock levels. We'll clean it up and release it next week. Ping me on here if I fail to do so :)

**Comment by adrian-stein** [comment]
@stevie-mayhew how goes the cleaning up?? :)

**Comment by digitweaks** [comment]
I'm also checking it out to see if there's any update release 

Envoyé de mon iPhone

**Comment by nimbleradmin** [comment]
@frankmullenger  @stevie-mayhew How is that WIP item you were cleaning up and releasing, did it ever get released? I really need the stock level stuff now.

**Comment by adrian-stein** [comment]
@frankmullenger  @stevie-mayhew How is that WIP item you were cleaning up and releasing, did it ever get released? I really need the stock level stuff now.
