### ISSUE TITLE
Display variation price in select option

### ISSUE THREAD

**Issue by mylesthedev** [swipestripe/silverstripe-swipestripe#22]
I was wondering if you could point me in the right direction with getting the price displaying in the option on the product page?

I see they are all in the data-map so I could potentially do it with javascript but I was hoping it would be possible to add in the form itself.

**Comment by mylesthedev** [comment]
I've quickly made this inside ProductForm.js which seem to work but PHP would be preferred.

/\* Quick hack to match variations to options and append the price */
    var product_variations = $('.product-form').data('map');
    var product_options = $('.attribute_option');
    product_options.children().map(function() {

```
    for (var i = 0; i < product_variations.length; i++){
        if(product_variations[i]['options'] == $(this).val()){
            $(this).append("&nbsp;&nbsp;-&nbsp;&nbsp;"+product_variations[i]['price'])
        }
    }

}).get();
```

**Comment by icecaster** [comment]
Hi Miles,

should be pretty straight forward to make a CartForm - Extension, select the variation dropdown and modifying it's options...

Let me know if you're stuck and I'll try to find an example.

Cheers

**Comment by mylesthedev** [comment]
Hey Tim,

If you have an example that would be great!

**Comment by frankmullenger** [comment]
@mediabeastnz the prices are usually associated with variations as opposed to options, if you have a single select field of options it can make sense to add the prices but if you have numerous options for a product the price might not accurately reflect each option..

**Comment by mylesthedev** [comment]
Good point... cheers.
