### ISSUE TITLE
Variations

### ISSUE THREAD

**Issue by gavro** [swipestripe/silverstripe-swipestripe#23]
I'm trying to set up a product which uses 4 different attributes in it's variations. I see that attributes are populated based on previous attribute sets (selects, data-map).

Trying to figure out how to display all possible options in all dropdowns based on everything that is enabled as a variation. What I'm getting is that the 3rd/4th dropdown is populated with **all** the options possible from added variations without looking back to option1/2 (to see if that variation is enabled at all). The pricehandling does only update if you make a valid selection, but as soon as you make a non-valid selection you can't add it to your cart.

Hmm, how to illustrate this...
For example:

```
attr1A - attr2A - attr3A
attr1A - attr2A - attr3B

attr1A - attr2B - attr3A
attr1A - attr2B - attr3B

attr1B - attr2A - attr3A

attr1B - attr2B - attr3A
```

If I select attr1B I should not be able to select attr3B. It is not added as a variation. But based on attr2A and attr2B i will still get 3B as an option (but I would not be able to add the product).

Any thoughts how this could be fixed?

**Comment by frankmullenger** [comment]
Hi @gavro, thanks again for raising this, does the commit above fix the issue for you?

**Comment by frankmullenger** [comment]
Closing this for now, please let me know if issue persists.
