### ISSUE TITLE
Adding an update to an existing order creates an additional, empty order

### ISSUE THREAD

**Issue by nbenn** [swipestripe/silverstripe-swipestripe#25]
I'm using SS 3.1.2 (silverstripe/silverstripe-framework@054b35ded7674f13ccad4cec8fe38372e2a001df, silverstripe/silverstripe-cms@e2fa3b7f2c208af4a33e7176c1a950396d423f19) and the lastest Swipestripe commit (5edaa5d1fa4300e9796baa097710441bebbbfabe).

For completeness:
- silverstripe/payment@65dfbe47e3ca6875fa61deabe7565fa11eac722a
- frankmullenger/silverstripe-payment-cheque@d5c861c55f0b13ea7f93f93f759a16a31fc11080

are also installed.

The issue I am raising is as follows: placing and paying for an order results in an entry like

![screen shot 2013-12-18 at 11 46 31](https://f.cloud.github.com/assets/3158446/1773433/812a638a-67e7-11e3-8d03-55691d983883.png)

To mark the order as shipped, a status update is added

![screen shot 2013-12-18 at 11 47 38](https://f.cloud.github.com/assets/3158446/1773441/b07cbfe8-67e7-11e3-88e0-dc5332f7ed38.png)

which in turn creates a new, but empty order

![screen shot 2013-12-18 at 11 47 55](https://f.cloud.github.com/assets/3158446/1773452/edf73542-67e7-11e3-8a13-3e264a92c699.png)

The new order is not linked to the previously created status update. This behaviour seems unintentional.

**Comment by frankmullenger** [comment]
Hey @nbenn, thanks for raising this. For some reason the Order_Update::onAfterWrite() was being run twice and the first time the Order was not associated with it, the commit above should fix the issue but please let me know if not.
