### ISSUE TITLE
Problems changing the quantity of an item.

### ISSUE THREAD

**Issue by ghost** [swipestripe/silverstripe-swipestripe#26]
When the quantity of an item is changed in the shopping cart and press the tab key will not change the total price.

Regards,
Jose A.

**Comment by frankmullenger** [comment]
@Josua2012 yes at present the cart is only updated when a user clicks the 'Update Cart" button and the form is submitted. I like your idea though and will keep it in mind as a feature to add in future.

**Comment by frankmullenger** [comment]
Going to close this for now Josua, but the feature you suggest has been noted thanks!
