### ISSUE TITLE
Unit tests: fix existing and add more

### ISSUE THREAD

**Issue by Zauberfisch** [swipestripe/silverstripe-swipestripe#35]
always good to have more tests, right?

Besides, it seems to be that a hand full of the tests are not passing.
@frankmullenger are the tests passing for you?
If you can confirm that all SwipeStripe related tests pass for you, I will look into my setup, otherwise I will update this issue with further details.

**Comment by frankmullenger** [comment]
Perhaps we should have Travis set up for this project or something. Last time I checked all tests passed for me but have just run them again and 4 of them fail based on the changes to Product image handling - so hopefully once that is sorted they will be passing again.

**Comment by frankmullenger** [comment]
@Zauberfisch unit tests passed for me today but only when run in isolation. For example, I had to remove the gallery module so that the extension for product images was not added - is this acceptable and can we close this ticket do you think?

**Comment by Zauberfisch** [comment]
I suppose so.
The issue of conflicts with other modules is probably covered by the ticket regarding namespaces.
