### ISSUE TITLE
Three or more Attributes on Product cause duplicate options in ProductForm dropdown.

### ISSUE THREAD

**Issue by TamaEaston** [swipestripe/silverstripe-swipestripe#43]
I've come across a bug and have replicated it on the SwipeStripe demo site: http://ss3.swipestripe.com/clothing/hats/cowboy-hat/

When three options are added to a product the middle option drop down has attributes appearing multiple times.

In the linked example the following variations have been set:
Inline images 1
![image](https://cloud.githubusercontent.com/assets/1066948/2910860/cfb373b4-d64d-11e3-8b82-5036d645c9cb.png)

This causes the middle drop down to display the following:
Inline images 2
![image](https://cloud.githubusercontent.com/assets/1066948/2910861/d9212a5e-d64d-11e3-86cc-13f748ff03ab.png)

**Comment by frankmullenger** [comment]
Thanks for reporting this @TamaEaston, pretty busy at the moment but hopefully one of us can have a look into this.

**Comment by Zauberfisch** [comment]
no time either, sorry :S

**Comment by stevie-mayhew** [comment]
I'm busy too, but will have some spare time on Saturday to have a look at this if its not too late for you :)

Jobs, eh? :smile:

**Comment by TamaEaston** [comment]
Any progress on this? It's holding up a site roll-out.

If there's anything I can do to help things along please let me know.

**Comment by frankmullenger** [comment]
@TamaEaston can you check the commit on my fork above to see if it fixes this issue please?
Edit: Actually another pull request fixes this issue so have merged that and closed mine.

**Comment by TamaEaston** [comment]
Thank you Frank. I'm tied up today but will check Monday at the latest.

**Comment by TamaEaston** [comment]
@frankmullenger - just to confirm, we have this now working successfully in production environment.

**Comment by frankmullenger** [comment]
@TamaEaston thanks for confirming mate.
