### ISSUE TITLE
Money precision needs to accept less than 2 decimal places

### ISSUE THREAD

**Issue by stevie-mayhew** [swipestripe/silverstripe-swipestripe#56]
Currencies such as Japanese Yen have no decimal place, currently the lower bound on decimal places is set to 2 (https://github.com/swipestripe/silverstripe-swipestripe/blob/f9295b18e817253f6e486b27800498250c9d1c4d/code/form/OrderForm.php#L320).

**Comment by silverstripe-elliot** [comment]
Cheers, I'll patch it up tonight. Ideally it should match up with what Zend/Currency.php uses in the framework (it's bounded between -1 and 30). I'll still leave it as "2" by default for backwards compatibility

**Comment by stevie-mayhew** [comment]
Awesome, thanks heaps @silverstripe-elliot

**Comment by silverstripe-elliot** [comment]
Pull request is here: https://github.com/swipestripe/silverstripe-swipestripe/pull/57
