### ISSUE TITLE
update composer.json & packagist

### ISSUE THREAD

**Issue by Zauberfisch** [swipestripe/silverstripe-swipestripe#60]
composer.json still contains links to `frankmullenger/silverstripe-swipestripe`    

https://packagist.org/packages/swipestripe/swipestripe also still references to `frankmullenger/silverstripe-swipestripe`

**Comment by Zauberfisch** [comment]
modules that have been moved from `frankmullenger` to `swipestripe` and no longer exist on `frankmullenger` are automatically forwarded by github though.

but we should change it either way.

**Comment by frankmullenger** [comment]
@Zauberfisch have changed in packagist, fixed for you now?

**Comment by Zauberfisch** [comment]
looks good

but on the following you missed the link to the issue tracker:
- https://packagist.org/packages/swipestripe/swipestripe-xero
- https://packagist.org/packages/swipestripe/swipestripe-gallery
- https://packagist.org/packages/swipestripe/swipestripe-flatfeetax

**Comment by frankmullenger** [comment]
@Zauberfisch yeah I noticed that but only have the ability to update the repo link when editing - might have to ping Packagist about it..

**Comment by frankmullenger** [comment]
@Zauberfisch come to think of it the issues URL is in composer.json so will have to update each repo.
