### ISSUE TITLE
cannot set decimal value

### ISSUE THREAD

**Issue by luukgruijs** [swipestripe/silverstripe-swipestripe#73]
Hi,

somehow it's impossible to set an decimal value as a product price. The strange thing is that i can set 15.00, but not 15.30. This gives an error that references to the framework/model/mysqldatabase file.

I see in the demo that this must be possible. Any idea how to fix this?

Thanks in advance.

**Comment by RuthAdele** [comment]
What is the error that you're getting? I don't think this is a problem with swipestripe (I'm using an install at the moment that has prices with decimal places - $14.99 etc)

**Comment by silverstripe-elliot** [comment]
Please post the exact error so we can have a look at it.

**Comment by luukgruijs** [comment]
Thanks for the fast response:

i have two errors:

[Error] Couldn't run query: INSERT INTO "Product_versions" ("Price", "Currency", "RecordID", "Version") VALUES (15,5, 'EUR', 31, 4) Column count doesn't match value count at row 1

[Error] Couldn't run query: UPDATE "Product" SET "Price" = 15,5 where "ID" = 31 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '5 where "ID" = 31' at line 1

Do you have an idea?

**Comment by silverstripe-elliot** [comment]
Where are you setting Price as 15,5?

**Comment by luukgruijs** [comment]
in the price field of the product. i'm setting the price as 15.50

**Comment by RuthAdele** [comment]
are you using a comma or a decimal place? 
(I think Euro is normally written E1.500,50 compared to the Australian way of $1,500.00)

**Comment by silverstripe-elliot** [comment]
Is this a vanilla installation of Swipestripe or have you made some custom class that extends Product? 

The issue with that error specifically is that the value "15,5" is making its way into the database query somehow. It's a bit worrying, since that implies the field isn't being sanitised

@RuthAdele I've never seen a price written like that!

**Comment by silverstripe-elliot** [comment]
I wonder if it has something to do with the PHP locale settings on your server?

**Comment by RuthAdele** [comment]
@silverstripe-elliot  yeah, its common use in many parts of Europe. I'm Australian, but I've done alot of travelling through Europe.
I agree it looks like the data isn't being escaped before it goes into the database. The currency field in SS does have validation on it preventing you from entering anything other than numbers etc, so maybe it isn't being escaped!

Simple answer would be to enter your price using a dot (rather than a comma) as your decimal place.

**Comment by luukgruijs** [comment]
i manually installed swipestripe and didn't write custom classes. The strange thing is that it works on another installation.

**Comment by silverstripe-elliot** [comment]
I wonder if you're having the same problems with localeconv() that @gavro was having in: https://github.com/swipestripe/silverstripe-swipestripe/pull/71. The Zend library in Silverstripe mangles the price for certain PHP locales.

**Comment by luukgruijs** [comment]
That would be strange, since i got it working on another local swipestripe installation. Is there a way to set these locale manually?

The only difference is that i installed silverstripe and the modules via composer on one and manually on the other

**Comment by silverstripe-elliot** [comment]
Yes. Use [setlocale](http://php.net/manual/en/function.setlocale.php) in your `mysite/_config.php` file.

**Comment by luukgruijs** [comment]
That was the problem.

i had these settings in my _config file:
i18n::set_locale('nl_NL');
setlocale(LC_ALL, 'nl_NL');
setlocale (LC_TIME, 'nl_NL.UTF-8');

i removed them and now they work.

Thanks for the great support!

**Comment by gavro** [comment]
Luuk,

Just wondering if you are having any issues on the front-end with money-presentation? I've had to add those locale setting to my config otherwise I got english .-notations. Hence the pull request to be able to use dutch locale @ front-end and force english @ back-end.

**Comment by luukgruijs** [comment]
yeah, i do have .-notations in the front-end. Thanks i will check the pull-request
