### ISSUE TITLE
Directly redirect to the cart instead of back to the product page.

### ISSUE THREAD

**Issue by luukgruijs** [swipestripe/silverstripe-swipestripe#79]
Hi,

I'm building a product where it's possible to buy just one product. Because of the fact we are only selling one product it would be nice to automatically redirect to the cart when you add the product to the cart. Now its redirecting back to the product page.

There is this variable $redirectURL in ProductForm.php. How can i change it so it redirects to the cart?

Thanks in advance

**Comment by icecaster** [comment]
in Product.ss use the 2nd parameter to set the redirect url:
$ProductForm(1,cart)

**Comment by luukgruijs** [comment]
Great, thanks!
